In [2]:
import torch
import torch.nn as nn

In [5]:
inputs = {'input_ids': torch.tensor([   1,   15, 1075,  126,  194,  430,  105,  873]), 'attention_mask': torch.tensor([1, 1, 1, 1, 1, 1, 1, 1]), 'label': torch.tensor(1)}
x = inputs['input_ids']
embeddings = nn.Embedding(num_embeddings=16000, embedding_dim=128)
sentence = embeddings(x).detach()
sentence.shape

torch.Size([8, 128])

In [6]:
d_model, n_heads = 128, 8
d_k = int(d_model/n_heads)
d_q, d_v = d_k, d_k
torch.nn.Parameter(torch.rand(d_model, d_k))

Parameter containing:
tensor([[0.1080, 0.2588, 0.1528,  ..., 0.5445, 0.1877, 0.8018],
        [0.4910, 0.7235, 0.8743,  ..., 0.1006, 0.0645, 0.4158],
        [0.0276, 0.1498, 0.7157,  ..., 0.3366, 0.6612, 0.2028],
        ...,
        [0.5456, 0.7573, 0.4561,  ..., 0.1805, 0.7653, 0.2535],
        [0.9660, 0.0091, 0.2226,  ..., 0.5059, 0.7477, 0.2053],
        [0.8256, 0.8324, 0.5988,  ..., 0.1746, 0.8806, 0.7699]],
       requires_grad=True)

In [29]:
W_q = torch.nn.Linear(in_features=d_model, out_features=d_k)
W_q

Linear(in_features=128, out_features=16, bias=True)

In [26]:
W_q(sentence).shape

torch.Size([8, 16])

In [30]:
keys = W_q(sentence)

In [35]:
keys.shape

torch.Size([8, 16])

In [36]:
keys.T.shape

torch.Size([16, 8])

In [37]:
keys.T == keys.transpose(-2, -1)

tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])

In [16]:
x.device

device(type='cpu')

In [15]:
pos_enc = nn.Embedding(1024, 128)
positions = torch.arange(0, len(x)).unsqueeze(dim=0)
embeddings(x), pos_enc(positions), embeddings(x)+pos_enc(positions)

(tensor([[-0.1927, -2.7106, -0.6197,  ...,  1.1473,  2.0553,  0.4151],
         [ 0.1421, -0.7689,  0.3769,  ...,  0.0697,  1.1415,  0.1970],
         [-1.8202, -1.3779,  1.0631,  ...,  0.1377,  0.0374,  1.6048],
         ...,
         [-0.7385, -0.2250, -1.9107,  ..., -0.1647,  1.0714, -0.9317],
         [-0.0153,  0.5112, -0.6501,  ...,  0.7190, -0.0085, -0.5314],
         [-0.4835,  0.1453, -0.5339,  ...,  0.5381,  0.3193,  0.6896]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[[-1.8459, -1.7282, -0.6483,  ...,  0.0543, -0.8648,  1.0076],
          [-2.0549, -0.8155, -0.5276,  ..., -0.2688, -0.6486, -0.3124],
          [ 0.1090,  0.5589,  1.1096,  ...,  0.3564,  1.5431, -0.2893],
          ...,
          [ 0.4605, -0.6430, -0.7065,  ...,  1.1937, -0.0493, -0.4530],
          [ 1.8162,  0.5795, -0.2745,  ..., -1.2953, -1.0593,  0.3853],
          [ 0.5429,  1.1721,  1.3245,  ...,  2.2241, -0.8260, -0.2536]]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[[-2.0386, -4.4388, -1.